In [4]:
pip install numpy

In [5]:
#importing numpy
import numpy as np


In [22]:
my_lst=[1,2,3,4]

arr=np.array(my_lst)

#array()--> creates an array based on the data type of the list 

In [14]:
type(arr)

numpy.ndarray

In [20]:
print(arr)

[1 2 3 4]


In [25]:
arr.shape

#shape of an array is the number of items in each dimension 

(4,)

In [32]:
my_lst1=[1,2,3,4]
my_lst2=[12,18,23,22]
my_lst3=[11,31,1,6]
arr=np.array([my_lst1,my_lst2,my_lst3])
print(arr)

[[ 1  2  3  4]
 [12 18 23 22]
 [11 31  1  6]]


In [33]:
arr.shape

#arr.shape--> returns the number of rows and number of columns

(3, 4)

In [40]:
arr.reshape(2,6)

#arr.reshape-->returns the same data with a new shape

array([[ 1,  2,  3,  4, 12, 18],
       [23, 22, 11, 31,  1,  6]])

In [42]:
arr.reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [41]:
arr.shape

(3, 4)

In [43]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [12, 18, 23, 22],
       [11, 31,  1,  6]])

In [44]:
arr

array([[ 1,  2,  3,  4],
       [12, 18, 23, 22],
       [11, 31,  1,  6]])

In [45]:
arr[:,:]
#first argument-->prints the array from 0th row till the last row
#second argument--> prints the array from 0th column till the last column


array([[ 1,  2,  3,  4],
       [12, 18, 23, 22],
       [11, 31,  1,  6]])

In [46]:
arr[:,2:3]

#accessing elements in a multi-dimensional array

array([[ 3],
       [23],
       [ 1]])

In [47]:
arr[0:,:3]

array([[ 1,  2,  3],
       [12, 18, 23],
       [11, 31,  1]])

In [48]:
arr[1:2,1:3]

array([[18, 23]])

In [6]:
arr=np.arange(1,10)
#arange()-->returns evenly spaced values within the given interval 

In [50]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr=np.arange(2,20,2)

In [52]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
arr=np.arange(1,10,0.5)

In [54]:
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [57]:
arr=np.linspace(1,10,num=50) 

#num--> number of samples to generate 
#by default ,it is 50

In [58]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [9]:
#copy and broadcasting
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1=arr
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1[3:]=100

In [13]:
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [15]:
arr1=np.copy(arr)
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [67]:
arr1[3:]=500

In [68]:
print(arr1)
print(arr)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 100 100 100 100 100 100]


In [19]:
###Some conditions very useful in Exploratory Data Analysis
arr=np.arange(1,10)
print(arr)
val=2 
arr<val

#only those elements are True that are less than val i.e. 2

[1 2 3 4 5 6 7 8 9]


array([ True, False, False, False, False, False, False, False, False])

In [20]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [22]:
#to get the exact values that are less than val 
arr[arr<val]

array([1])

In [23]:
#likewise
arr[arr<500]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#creating arrays and reshape 
arr= np.arange(0,10).reshape(2,5)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
arr1=np.arange(1,20,2).reshape(5,2)
arr2=np.arange(0,10).reshape(2,5)

In [31]:
arr1

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [40]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
arr1*arr2

#only for square matrices 

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [42]:
arr3=np.matmul(arr1,arr2)
arr3
#for matrix multiplication 

array([[ 15,  19,  23,  27,  31],
       [ 35,  47,  59,  71,  83],
       [ 55,  75,  95, 115, 135],
       [ 75, 103, 131, 159, 187],
       [ 95, 131, 167, 203, 239]])

In [44]:
#some more in-built functions 

np.ones(4)

#by default , the data type is float 

array([1., 1., 1., 1.])

In [45]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [46]:
np.random.rand(3)

array([0.93666187, 0.99139472, 0.32351294])

In [47]:
np.random.rand(3,3)

array([[0.54200488, 0.53421252, 0.73825207],
       [0.34646488, 0.40200888, 0.93358492],
       [0.31233852, 0.71477853, 0.82072067]])

In [49]:
np.random.randn(3,4)
#the output changes , in every execution since it is random distribution 

array([[ 2.4198158 , -0.37417301,  0.73839932, -0.94413587],
       [-1.0410311 ,  0.25003262, -0.80016331, -0.18559752],
       [-2.46602251, -0.34810774,  0.57332515,  0.28966609]])